# メインメニュー
[[main]]
name = "ホーム"
url = "/"
weight = 1

[[main]]
name = "製品"
url = "/product"
weight = 2

[[main]]
name = "ブログ"
url = "/blog"
weight = 3

[[main]]
name = "会社概要"
url = "/about"
weight = 4

[[main]]
name = "お問い合わせ"
url = "/contact"
weight = 5

[[main]]
name = "その他"
weight = 6

[[main]]
parent = "その他"
name = "メンバー"
url = "/authors"

[[main]]
parent = "その他"
name = "カテゴリー"
url = "/categories"

# フッターメニュー
[[footer]]
name = "会社概要"
url = "/about"
weight = 1

[[footer]]
name = "お問い合わせ"
url = "mailto:alroborol@gmail.com"
weight = 2

[[footer]]
name = "プライバシーポリシー"
url = "/privacy-policy"
weight = 3
